# This is a basic workflow to help you get started with Actions

name: First CI on Github

on:
  push:
    branches: [ master, develop ]


jobs:
  first_job:
    name: test
    runs-on: [ubuntu-latest]
    steps:
      - name: first_step
        uses: actions/checkout@v2.1.0
        
      - name: list of files
        run: ls
        
      - name: Run test
        run: npm test
        
      
         
