# This is a basic workflow to help you get started with Actions

name: Build

on:
  push:
    branches: [ master, develop ]


jobs:
  first_job:
    name: test
    runs-on: [ubuntu-latest]
    steps:

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12
      - name: checkout
        uses: actions/checkout@v2.1.0

      - name: list env
        run: ./env.sh

      - name: Install packages
        run: npm install

      - name: Run test
        run: npm test



